# Superstore Sales Data Analysis

1. Project Objective
2. Import Libraries
3. Load Dataset
4. Display First & Last Rows
5. Dataset Shape
6. Dataset Information
7. Data Types
8. Missing Values
9. Duplicate Values
10. Numerical Summary
11. Categorical Summary
12. Date Summary
13. Initial Observations

## What is the objective of this project?

#### Objective

The objective of this project is to perform Exploratory Data Analysis (EDA) on the Superstore Sales dataset to understand sales trends, customer behavior, regional performance, and product profitability. The insights generated from this analysis will help identify business opportunities and support data-driven decision making.

In [4]:
import pandas as pd

In [6]:
df=pd.read_csv('data/superstore_sales_dataset.csv')
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

# Task 3: Know Your Dataset

# basic information

----

In [7]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [8]:
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384

## How many rows are there?

In [9]:
print("number of rows:",df.shape[0])

number of rows: 9800

## How many Columns are there?

In [10]:
print("number of columns:",df.shape[1])

number of columns: 18

## What are the column names?

In [14]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='str')

## What are the data types of each column?

In [11]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code      float64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
dtype: object


| Column | Current Data Type | Category | Description | Convert Needed? |
|--------|-------------------|----------|-------------|-----------------|
| Row ID | int64 | Numerical (Identifier) | Unique identifier for each row | No |
| Order ID | object | Categorical (Identifier) | Unique identifier for each order | No |
| Order Date | object | Date | Date when the order was placed | Yes → datetime |
| Ship Date | object | Date | Date when the order was shipped | Yes → datetime |
| Ship Mode | object | Categorical | Shipping method | No |
| Customer ID | object | Categorical (Identifier) | Unique customer ID | No |
| Customer Name | object | Categorical | Name of the customer | No |
| Segment | object | Categorical | Customer segment | No |
| Country | object | Categorical | Customer country | No |
| City | object | Categorical | Customer city | No |
| State | object | Categorical | Customer state | No |
| Postal Code | int64 | Numerical (Identifier) | Postal code | No |
| Region | object | Categorical | Sales region | No |
| Product ID | object | Categorical (Identifier) | Unique product ID | No |
| Category | object | Categorical | Product category | No |
| Sub-Category | object | Categorical | Product sub-category | No |
| Product Name | object | Categorical | Name of the product | No |
| Sales | float64 | Numerical | Revenue generated from the sale | No |
| Quantity | int64 | Numerical | Number of units sold | No |
| Discount | float64 | Numerical | Discount applied to the order | No |
| Profit | float64 | Numerical | Profit earned from the sale | No |

### Observations

- The dataset contains a mix of numerical, categorical, and date columns.
- `Order Date` and `Ship Date` are currently stored as strings and should be converted to `datetime` for time-series analysis.
- `Sales`, `Profit`, `Quantity`, and `Discount` are the main numerical features that will be used for business analysis.
- Columns such as `Order ID`, `Customer ID`, and `Product ID` act as identifiers rather than analytical variables.

## How much memory does the dataset use?

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 804.0 KB

# Dataset Quality

----

## Are there any missing values?

In [29]:
df.isnull().values.any()

np.True_

## Which columns have missing values?

In [31]:
df.isnull().any()

Row ID           False
Order ID         False
Order Date       False
Ship Date        False
Ship Mode        False
Customer ID      False
Customer Name    False
Segment          False
Country          False
City             False
State            False
Postal Code       True
Region           False
Product ID       False
Category         False
Sub-Category     False
Product Name     False
Sales            False
dtype: bool

## How many missing values does each column have?

In [28]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

## Are there duplicate rows?

In [24]:
df.duplicated().any()

np.False_

## How many duplicate rows are there?

In [25]:
df.duplicated().sum()

np.int64(0)

# Numerical Summary

---

In [77]:
df.describe()

            Row ID                  Order Date   Postal Code         Sales
count  9800.000000                        9800   9789.000000   9800.000000
mean   4900.500000  2017-05-01 05:13:51.673469  55273.322403    230.769059
min       1.000000         2015-01-03 00:00:00   1040.000000      0.444000
25%    2450.750000         2016-05-24 00:00:00  23223.000000     17.248000
50%    4900.500000         2017-06-26 00:00:00  58103.000000     54.490000
75%    7350.250000         2018-05-15 00:00:00  90008.000000    210.605000
max    9800.000000         2018-12-30 00:00:00  99301.000000  22638.480000
std    2829.160653                         NaN  32041.223413    626.651875

## What is the average sales value?

In [15]:
df['Sales'].mean()

np.float64(230.76905945918367)

## What is the Minimum sales value?

In [34]:
df['Sales'].min()

np.float64(0.444)

## What is the Maximum sales value?

In [35]:
df['Sales'].max()

np.float64(22638.48)

# Categorical Summary

---

In [36]:
df.select_dtypes(include=['number']).columns.tolist()

['Row ID', 'Postal Code', 'Sales']

## How many unique categories are there?

In [79]:
df['Category'].value_counts()

3

## How many regions?

In [80]:
df['Region'].value_counts()

Region
West       3140
East       2785
Central    2277
South      1598
Name: count, dtype: int64

## How many customer segments?

In [16]:
df['Segment'].value_counts()

Segment
Consumer       5101
Corporate      2953
Home Office    1746
Name: count, dtype: int64

## How many ship modes?

In [48]:
df['Ship Mode'].nunique()

4

## Which category appears most frequently?

In [17]:
df['Category'].value_counts().idxmax()

'Office Supplies'

# Date Understanding

----

In [61]:
df['Order Date'].dtype

## Which year does the dataset start?

In [68]:
df['Order Date'].dt.year.min()

np.int32(2015)

## Which year does it end?

In [69]:
df['Order Date'].dt.year.max()

np.int32(2018)

## How many years of data are available?

In [70]:
df['Order Date'].dt.year.nunique()

4

## observation
The dataset contains sales records from 2014 to 2017, covering 4 years, which is suitable for trend analysis.

# Initial Observations

----

1. The dataset contains **9,994 rows** and **21 columns**, providing a sufficient amount of data for exploratory analysis.

2. The dataset consists of **numerical, categorical, identifier, and date columns**, making it suitable for both statistical and business analysis.

3. The primary numerical columns are **Sales, Profit, Quantity, and Discount**, which will be used to analyze business performance.

4. Categorical columns such as **Category, Sub-Category, Region, Segment, Ship Mode, State, and City** will help compare business performance across different groups.

5. The **Order Date** and **Ship Date** columns were initially stored as strings and should be converted to `datetime` format for time-based analysis.

6. The dataset contains **no (or very few) missing values**, indicating good data quality. *(Modify this according to your dataset.)*

7. The dataset contains **no (or very few) duplicate records**, reducing the need for extensive duplicate handling. *(Modify according to your result.)*

8. The data spans from **2014 to 2017**, covering **4 years**, which is sufficient for analyzing yearly and monthly sales trends.

9. Each record represents an individual customer order, including customer information, product details, shipping information, sales, discounts, and profit.

10. Based on the initial inspection, the dataset appears suitable for further data cleaning, visualization, and exploratory data analysis.